services:
  postgres:
    image: postgres:15       
    container_name: task_manager_postgres
    restart: always
    environment:
      POSTGRES_USER: t-trent
      POSTGRES_PASSWORD: t-trent
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
